### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [lubang/hugo-hello-programmer-theme#2]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:
![image](https://user-images.githubusercontent.com/712534/37667965-5c9527f2-2c74-11e8-9991-5444d246029a.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by lubang** [comment]
OK. I'll try fix it today. Thanks for the same issue.
Please wait 🙏

**Comment by lubang** [comment]
Fix it. 106a4c43c397197fa056de816aaa8b0ca947a67e
