### ISSUE TITLE
Category & tag page 설정 건

### ISSUE THREAD

**Issue by JmyL** [lubang/hugo-hello-programmer-theme#3]
안녕하세요 :)

블로그 테마에 카테고리와 태그 메뉴가 없어서 이리저리 찾다가 작업하신 theme를 다운받고 적용해 보았습니다.

http://jmyl.gitlab.io/

작업에 감사합니다. 앞으로 조금씩 수정해서 호스팅하시는 블로그와는 다른 느낌이 될 수 있도록 작업해 보려고 합니다.

Categories와 tags menu가 보이지 않는데, 어떻게 작업하면 좋은지 여쭤봅니다.

아마도 theme이 아닌 별도의 설정이 있는 것 같은데 잘 못 찾겠네요.

**Comment by lubang** [comment]
JmyL 님이 작업하신 테마도 느낌이 좋네요.
Categories, tags 메뉴는 Markdown 작성 시 다음과 같이 categories, tags 필드를 추가해주시면 됩니다.

<pre>
---
title: "Vue #01. Vue.js 프로젝트 구성 (SPA)"
date: 2018-03-24T13:31:33+09:00
categories: ["web"]
tags: ["웹", "vue", "spa", "frontend", "become-a-celeb"]
draft: true
---

Vue.js 를 이용한 SPA(Single page application) 개발의 시작에서 배포까지 정리하였다. 본 글은 vue의 특징, 장점, Getting started는 이미 읽고 대략 vue를 본격적으로 프로젝트에 도입을 하는 사람들을 위한 내용이다.

**Vue를 이용한 SPA 프로젝트!**
</pre>

**Comment by JmyL** [comment]
네 답변 감사합니다. 그런데 말씀하신 대로 해 두었는데도 안 되어서요;;

https://gitlab.com/jmyl/jmyl.gitlab.io/blob/master/content/post/git/atom-git-plus.md 여기입니다.

**Comment by lubang** [comment]
알려주신 Post를 그대로 제 블로그에 등록해보았는데 잘 표시가 되네요. :(
위 링크의 내용을 그대로 content/post/atom-git-plus.md 의 위치에 작성하고 `hugo server -w`로 확인한 화면입니다.

![image](https://user-images.githubusercontent.com/3124653/38452615-9e51bf72-3a82-11e8-83c6-13a38119bc8d.png)

저도 별도의 설정을 한 기억은 없고 Post마다 categories, tags만 작성하면 되었기 때문에 이런 경우는 처음이네요. 
참고로 https://github.com/lubang/blog-lulab-net 에 실제로 https://blog.lulab.net 의 Hugo 문서 및 세팅을 그대로 올리고 있습니다.

현재 빌드 시 사용하고 있는 휴고 버전은 다음과 같습니다.
> hugo version
> Hugo Static Site Generator v0.37.1 darwin/amd64 BuildDate:

도움이 되면 좋겠는데 현재 바로 확인이 가능한 부분은 여기까지네요.

다이나믹한 움직임 및 반응성을 가져가기 위해서 테마를 업데이트 예정인데
업데이트 작업을 하며 위 내용을 좀 더 살펴보고 해결 방법을 찾는다면 바로 공유하도록 하겠습니다.

**Comment by JmyL** [comment]
확인 감사합니다 :) 저도 blog.lulab.net 내용을 빌드해 보고 알려드려야겠네요.

제 버전은 다음과 같습니다.

```
Hugo Static Site Generator v0.25.1 linux/amd64 BuildDate: 2017-08-03T17:06:42+09:00
```

Ubuntu에 등록된 저장소로 설치하니까 요 버전이 설치되네요.

**Comment by JmyL** [comment]
흠... https://github.com/lubang/blog-lulab-net 이 아이를 clone 받아서 `hugo server -w` 실행했더니 

```
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
15 regular pages created
134 other pages created
0 non-page files copied
0 paginator pages created
7 categories created
50 tags created
total in 31 ms
Watching for changes in /home/jmyl/git/blog-lulab-net/{content,static}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

요롷게 출력은 되는데, 정작 http://localhost:1313/ 에 접속하면 아무것도 안 나옵니다;; ㅎㅎ

**Comment by JmyL** [comment]
https://discourse.gohugo.io/t/how-to-add-tag-and-category/3202/5#post_6

여기를 보니까 config.toml에 다음 내용을 넣으라는 이야기가 있는데요,

```yml
[taxonomies]
   tag = "tags"
   category = "categories"
```

요골 해도 안되네요;;

아무래도 https://gohugo.io/content-management/taxonomies/ 요골 좀 정독 해 봐야겠습니다 ㅎㅎ

**Comment by lubang** [comment]
### blog-lulab-net repo clone 방법
아마, Theme 파일이 추가되지 않은 것 같네요. 일단 blog-lulab-net 레포지토리는 submodule을 포함하고 있어서 다음 명령어로 clone 하시면 theme 파일까지 함께 다운 받게 되어있습니다.

```
$ git clone --recurse-submodules  https://github.com/lubang/blog-lulab-net
$ cd blog-lulab-net
$ hugo server -w
```
제가 새로 받아서 테스트 해보았어요! 위와 같이 해보시면 잘 동작할 것으로 예상합니다 :)

### config.toml 의 taxonomies
taxonomies를 따로 설정하지 않은 이유는 tags, categories가 기본값이라 따로 설정하진 않았어요.

**Comment by JmyL** [comment]
아.. submodule로 해 놓으신 걸 봤었는데 깜빡했습니다. 확인해 볼께요 :) 감사합니다.

**Comment by JmyL** [comment]
네, submodule까지 받으니까 잘 됩니다.

제 블로그에서 잘 되지 않던 문제는 hugo version 문제였던 것 같습니다.

Docker image를 `publysher/hugo`로 사용하다가 `registry.gitlab.com/pages/hugo:latest`를 사용하니 문제 없네요.

감사합니다. Close하겠습니다.
