### ISSUE TITLE
How to modify korean language to other language?

### ISSUE THREAD

**Issue by 1iver** [lubang/hugo-hello-programmer-theme#5]
Thanks for your theme. It's beautiful, I like it. But it seems that I have no way but to change the content of layout directly. Does any other elegant way exists? like i18n.

**Comment by lubang** [comment]
@1iver Thanks for your consideration. Actually I think that i18n is good solution for other languages. So I'm developing it soon. Please wait a few days.

**Comment by lubang** [comment]
@1iver You can check i18n latest commit on master :) 0a346f10252f8fb38566944950f70db5867ab735 You can pull-request for any languages.
Thanx for your idea 👍
